# Site settings
title: MC Blog
SEOTitle: MC Blog | 陈铭杰的博客
header-img: img/home-mc-bg.jpg
email: echo TWljaGFlbF9DaGVuX0NTQGZveG1haWwuY29t | base64 -D
description: "\" Fiat Lux \""
keyword: "陈铭杰，Michael Chen, Mingjie Chen"
url: "https://michaelchen.xyz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
zhihu_username:     MichaelChen1999
github_username:    MessiahChen
linkedin_username:  Michael-Chen-CS
gitee_username:     MichaelChen1999
facebook_username:  MichaelChen1999
#weibo_username:     MichaelChen1999
#douban_username:    MichaelChen1999
#twitter_username:   huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: MichaelChen1999

# Netease settings
netease_comment: false

# valine
valine_comment:
  enable: true
  # app_id
  leancloud_appid: I3TqTs4Gki9fnQKXA2fnkDii-gzGzoHsz
  # app_key
  leancloud_appkey: KkAfl81x2sk5zYVpI0RHQYQD
  # placeholde (not work)
  placeholder: Leave your comments here!!!

# Cool Push Skey
cool_push_key: a26a09402ee4f64b8b3aa988196238f9

# Gitalk
gitalk:
  enable: false                                              #是否开启Gitalk评论
  clientID: 4e18638fd009d713bb55                            #生成的clientID
  clientSecret: c8e52c093b232c89219a6dc9daec48346fadd28d    #生成的clientSecret
  repo: MessiahChen.github.io                               #仓库名称
  owner: MessiahChen                                        #github用户名
  admin: MessiahChen
  distractionFreeMode: true                                 #是否启用类似FB的阴影遮罩

# Analytics settings

# Baidu Analytics
ba_track_id: '85028445bda879fb573cb2049d846436'

# Google Analytics
ga_track_id: 'UA-172728681-1'            # Format: UA-xxxxxx-xx
ga_domain: MichaelChen.xyz



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "veni vidi vici<br>我来 我见 我征服"
sidebar-avatar: /img/avatar-mc.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "[Carl Li]",
        href: "https://portfolio.lalxyy.me/"
    },
    {
        title: "[William Choe]",
        href: "https://www.williamchoe.com/"
    },
    {
      title: "[白]",
      href: "https://forself.me"
    },
    {
      title: "[Scott Ma]",
      href: "https://mhsfire.cn/"
    },
    {
      title: "[Benny Chen]",
      href: "https://bcwingnut.github.io/"
    },
    {
      title: "[Raven Xu]",
      href: "https://ravenxu.top"
    }

]
